services:
  postgres:
    build:
      context: .
    container_name: ContDBpractMod3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: p4ssw0rdDB
      POSTGRES_DB: credenciales
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    driver: local
